name: advent of code ci
on:
  push:
    branches:
      - 'main'

jobs:
  aoc-ts-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - uses: actions/setup-node@5ef044f9d09786428e6e895be6be17937becee3a
        with:
          node-version: 18

      - run: npm install

      - name: Run tests
        run: npm run test

  aoc-go-ci:
      runs-on: ubuntu-latest
      steps:
          - name: Check out repo code
            uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

          - name: Set up go
            uses: actions/setup-go@49bc3307c5d359429e8aee983859eb8dfad28c6b
            with:
                go-version: '^1.21.0'

          - name: Run tests
            run: |
                go test -v ./...
